USE [INFRA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AtividadePacote](
	[Id] [numeric](10, 0) IDENTITY NOT NULL,
	[Id_pacote] [numeric](10, 0) NOT NULL,
	[Descricao] [varchar](500) NOT NULL,
	[Tempo_previsto] [numeric](5, 2) NOT NULL,
	[Tempo_realizado] [numeric](5, 2) NOT NULL,
	[Possui_tarefas] [bit] NOT NULL,
	[Status] [char](1) NOT NULL,
 CONSTRAINT [AtividadePacote_Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[AtividadePacote]  WITH CHECK ADD  CONSTRAINT [FK_AtividadePacote_Pacote] FOREIGN KEY([Id_pacote])
REFERENCES [dbo].[Pacote] ([Id])
GO

ALTER TABLE [dbo].[AtividadePacote] CHECK CONSTRAINT [FK_AtividadePacote_Pacote]
GO

CREATE NONCLUSTERED INDEX [AtividadePacote_Pacote] ON [dbo].[AtividadePacote]
(
	[Id_pacote] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE UNIQUE NONCLUSTERED INDEX [AtividadePacote_Pacote_Descricao] ON [dbo].[AtividadePacote] 
(
	[Id_pacote] ASC,
	[Descricao] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
