USE [INFRA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EquipePacote](
	[Id] [numeric](10, 0) IDENTITY NOT NULL,
	[Id_pacote] [numeric](10, 0) NOT NULL,
	[Id_usuario] [numeric](10, 0) NOT NULL,
 CONSTRAINT [EquipePacote_Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[EquipePacote]  WITH CHECK ADD  CONSTRAINT [FK_EquipePacote_Pacote] FOREIGN KEY([Id_pacote])
REFERENCES [dbo].[Pacote] ([Id])
GO

ALTER TABLE [dbo].[EquipePacote] CHECK CONSTRAINT [FK_EquipePacote_Pacote]
GO

ALTER TABLE [dbo].[EquipePacote]  WITH CHECK ADD  CONSTRAINT [FK_EquipePacote_Usuario] FOREIGN KEY([Id_usuario])
REFERENCES [dbo].[Usuario] ([Id])
GO

ALTER TABLE [dbo].[EquipePacote] CHECK CONSTRAINT [FK_EquipePacote_Usuario]
GO

CREATE NONCLUSTERED INDEX [EquipePacote_Pacote] ON [dbo].[EquipePacote]
(
	[Id_pacote] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX [EquipePacote_Usuario] ON [dbo].[EquipePacote]
(
	[Id_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE UNIQUE NONCLUSTERED INDEX [EquipePacote_Pacote_Usuario] ON [dbo].[EquipePacote]
(
	[Id_pacote] ASC,
	[Id_usuario] ASC	
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
